### ISSUE TITLE
มีโปรเจ็คแปลเกมอื่นๆไหมครับ

### ISSUE THREAD

**Issue by watchakorn-18k** [nekopaldee/helltaker_thai_localization#3]
ตอนนี้ผมแปล GTA V เผื่อสนใจอยากจะช่วยๆกันครับ 55

**Comment by nekopaldee** [comment]
ตอนนี้กำลังทำ NieR Automata อยู่ครับผม ส่วน GTA V ผมขอผ่านดีกว่าครับ ไม่เคยเล่นเลย 5555 ขอโทษด้วยนะครับ

**Comment by watchakorn-18k** [comment]
ไม่มีปัญหาครับผม เรื่อง NieR Automata เอาลงใน repo ได้ก็ดีครับผมเดี๋ยวผมจะช่วยแปล 5555
