### ISSUE TITLE
รบกวนแนะนำวิธี extract และ compress ไฟล์ asset  หน่อยได้หรือเปล่าครับ 

### ISSUE THREAD

**Issue by watchakorn-18k** [nekopaldee/helltaker_thai_localization#4]
พอดีจะลองแปล Going Medieval หรือทางทีมงานจะแปลก็พร้อมยินดีช่วยครับผม ขอบคุณครับ

**Comment by nekopaldee** [comment]
ขอโทษที่ตอบช้านะครับ พอดีผมเพิ่งมีเวลาว่าง ทางผมคงไม่สามารถให้คำแนะนำตรงนี้ได้นะครับ พอดีว่าทางนี้ไม่มีเกม และไม่เคยเล่นเกมนี้ด้วยน่ะครับ ต้องขออภัยด้วยนะครับ
